# The Site Configuration

# Import the theme
theme: jekyll-theme-chirpy

# The language of the webpage › http://www.lingoes.net/en/translator/langcode.htm
# If it has the same name as one of the files in folder `_data/locales`, the layout language will also be changed,
# otherwise, the layout language will use the default value of 'en'.
lang: uz

# jekyll-seo-tag settings › https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
# ↓ --------------------------

title: Abdulhafiz Davlatov                         # the main title

tagline: |
  Senior Java Developer<br>
  <i class="fas fa-map-marker-alt" title="Location"></i> Uzbekistan

description: >-                        # used by seo meta and the atom feed
  Blog and cv

# fill in the protocol & hostname for your site, e.g., 'https://username.github.io'
url: "https://auzcoder.github.io"

github:
  username: auzcoder             # change to your github username

social:
  # Change to your full name.
  # It will be displayed as the default author of the posts and the copyright owner in the Footer
  name: Abdulhafiz Davlatov
  email: auz.offical@gmail.com
  links:
    # The first element serves as the copyright owner's link
    - https://github.com/auzcoder       # change to your github homepage
    # Uncomment below to add more social links
    # - https://www.facebook.com/username
    # - https://www.linkedin.com/in/username

# Site Verification Settings
webmaster_verifications:
  google: # fill in your Google verification code
  bing: # fill in your Bing verification code
  alexa: # fill in your Alexa verification code
  yandex: # fill in your Yandex verification code
  baidu: # fill in your Baidu verification code
  facebook: # fill in your Facebook verification code

# ↑ --------------------------
# The end of `jekyll-seo-tag` settings

# Web Analytics Settings
# analytics:
#   google:
#     id: # fill in your Google Analytics ID
#   goatcounter:
#     id: srzhka # fill in your GoatCounter ID

# Pageviews settings
# pageviews:
#   provider: goatcounter

# Prefer color scheme setting.
#
# Note: Keep empty will follow the system prefer color by default,
# and there will be a toggle to switch the theme between dark and light
# on the bottom left of the sidebar.
#
# Available options:
#
#     light  - Use the light color scheme
#     dark   - Use the dark color scheme
#
theme_mode: dark   # [light|dark]

# The CDN endpoint for images.
# Notice that once it is assigned, the CDN url
# will be added to all image (site avatar & posts' images) paths starting with '/'
#
# e.g. 'https://cdn.com'
img_cdn:

# the avatar on sidebar, support local or CORS resources
# avatar: assets/img/profile.jpg

# boolean type, the global switch for TOC in posts.
toc: true

# comments:
#   # Global switch for the post comment system. Keeping it empty means disabled.
#   active: giscus # [disqus | utterances | giscus]
#   # The provider options are as follows:
#   disqus:
#     shortname: # fill with the Disqus shortname. › https://help.disqus.com/en/articles/1717111-what-s-a-shortname
#   # utterances settings › https://utteranc.es/
#   utterances:
#     repo: # <gh-username>/<repo>
#     issue_term: # < url | pathname | title | ...>
#   # Giscus options › https://giscus.app
#   giscus:
#     repo: auzcoder/auzcoder.github.io            # <gh-username>/<repo>
#     repo_id: R_kgDOIQE0Mw
#     category: General
#     category_id: DIC_kwDOIQE0M84CSyPR
#     mapping:          # optional, default to 'pathname'
#     input_position:   # optional, default to 'bottom'
#     lang:             # optional, default to the value of `site.lang`
#     reactions_enabled: # optional, default to the value of `1`

# Self-hosted static assets, optional › https://github.com/cotes2020/chirpy-static-assets
